hydra:
  run:
    dir: ./training/outputs/${experiment_name}/${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - train_transforms@data.train_transforms: default
  - val_transforms@data.val_transforms: default
  - _self_

experiment_name: Loaders
seed: 42
warmup:
  enabled: True
  epochs: 3
  optimizer:
    weight_decay: 0.01
    param_groups:
      - layer_name: fc
        lr: 2e-3
training:
  epochs: 25
  loss_fn:
    label_smoothing: 0.1
    sampling_weight_scale: 0.5
  optimizer:
    weight_decay: 0.01
    param_groups:
      - layer_name: layer3
        lr: 1e-4
      - layer_name: layer4
        lr: 1e-4
      - layer_name: fc
        lr: 1e-3
model:
  name: resnet50
  dropout: 0.5
data:
  n_classes: 50
  split_seed: 42
  train_perc: 1.0
  valid_size: 0.15
  dataloader:
    batch_size: 32
    num_workers: 4